<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Enum.proto
 */


namespace PkgClient\Protocol\Enum;

/**
 * Protobuf enum : PkgClient.Protocol.Enum.EggIncubatorType
 */
class EggIncubatorType extends \Protobuf\Enum
{

    /**
     * INCUBATOR_UNSET = 0
     */
    const INCUBATOR_UNSET_VALUE = 0;

    /**
     * INCUBATOR_DISTANCE = 1
     */
    const INCUBATOR_DISTANCE_VALUE = 1;

    /**
     * @var \PkgClient\Protocol\Enum\EggIncubatorType
     */
    protected static $INCUBATOR_UNSET = null;

    /**
     * @var \PkgClient\Protocol\Enum\EggIncubatorType
     */
    protected static $INCUBATOR_DISTANCE = null;

    /**
     * @return \PkgClient\Protocol\Enum\EggIncubatorType
     */
    public static function INCUBATOR_UNSET()
    {
        if (self::$INCUBATOR_UNSET !== null) {
            return self::$INCUBATOR_UNSET;
        }

        return self::$INCUBATOR_UNSET = new self('INCUBATOR_UNSET', self::INCUBATOR_UNSET_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\EggIncubatorType
     */
    public static function INCUBATOR_DISTANCE()
    {
        if (self::$INCUBATOR_DISTANCE !== null) {
            return self::$INCUBATOR_DISTANCE;
        }

        return self::$INCUBATOR_DISTANCE = new self('INCUBATOR_DISTANCE', self::INCUBATOR_DISTANCE_VALUE);
    }

    /**
     * @param int $value
     * @return \PkgClient\Protocol\Enum\EggIncubatorType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::INCUBATOR_UNSET();
            case 1: return self::INCUBATOR_DISTANCE();
            default: return null;
        }
    }


}

