<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Enum.proto
 */


namespace PkgClient\Protocol\Enum;

/**
 * Protobuf enum : PkgClient.Protocol.Enum.FortRenderingType
 */
class FortRenderingType extends \Protobuf\Enum
{

    /**
     * DEFAULT = 0
     */
    const DEFAULT_VALUE = 0;

    /**
     * INTERNAL_TEST = 1
     */
    const INTERNAL_TEST_VALUE = 1;

    /**
     * @var \PkgClient\Protocol\Enum\FortRenderingType
     */
    protected static $DEFAULT = null;

    /**
     * @var \PkgClient\Protocol\Enum\FortRenderingType
     */
    protected static $INTERNAL_TEST = null;

    /**
     * @return \PkgClient\Protocol\Enum\FortRenderingType
     */
    public static function DEFAULT()
    {
        if (self::$DEFAULT !== null) {
            return self::$DEFAULT;
        }

        return self::$DEFAULT = new self('DEFAULT', self::DEFAULT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\FortRenderingType
     */
    public static function INTERNAL_TEST()
    {
        if (self::$INTERNAL_TEST !== null) {
            return self::$INTERNAL_TEST;
        }

        return self::$INTERNAL_TEST = new self('INTERNAL_TEST', self::INTERNAL_TEST_VALUE);
    }

    /**
     * @param int $value
     * @return \PkgClient\Protocol\Enum\FortRenderingType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::DEFAULT();
            case 1: return self::INTERNAL_TEST();
            default: return null;
        }
    }


}

