<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Enum.proto
 */


namespace PkgClient\Protocol\Enum;

/**
 * Protobuf enum : PkgClient.Protocol.Enum.FortType
 */
class FortType extends \Protobuf\Enum
{

    /**
     * GYM = 0
     */
    const GYM_VALUE = 0;

    /**
     * CHECKPOINT = 1
     */
    const CHECKPOINT_VALUE = 1;

    /**
     * @var \PkgClient\Protocol\Enum\FortType
     */
    protected static $GYM = null;

    /**
     * @var \PkgClient\Protocol\Enum\FortType
     */
    protected static $CHECKPOINT = null;

    /**
     * @return \PkgClient\Protocol\Enum\FortType
     */
    public static function GYM()
    {
        if (self::$GYM !== null) {
            return self::$GYM;
        }

        return self::$GYM = new self('GYM', self::GYM_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\FortType
     */
    public static function CHECKPOINT()
    {
        if (self::$CHECKPOINT !== null) {
            return self::$CHECKPOINT;
        }

        return self::$CHECKPOINT = new self('CHECKPOINT', self::CHECKPOINT_VALUE);
    }

    /**
     * @param int $value
     * @return \PkgClient\Protocol\Enum\FortType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::GYM();
            case 1: return self::CHECKPOINT();
            default: return null;
        }
    }


}

