<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Enum.proto
 */


namespace PkgClient\Protocol\Enum;

/**
 * Protobuf enum : PkgClient.Protocol.Enum.InventoryUpgradeType
 */
class InventoryUpgradeType extends \Protobuf\Enum
{

    /**
     * UPGRADE_UNSET = 0
     */
    const UPGRADE_UNSET_VALUE = 0;

    /**
     * INCREASE_ITEM_STORAGE = 1
     */
    const INCREASE_ITEM_STORAGE_VALUE = 1;

    /**
     * INCREASE_POKEMON_STORAGE = 2
     */
    const INCREASE_POKEMON_STORAGE_VALUE = 2;

    /**
     * @var \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    protected static $UPGRADE_UNSET = null;

    /**
     * @var \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    protected static $INCREASE_ITEM_STORAGE = null;

    /**
     * @var \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    protected static $INCREASE_POKEMON_STORAGE = null;

    /**
     * @return \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    public static function UPGRADE_UNSET()
    {
        if (self::$UPGRADE_UNSET !== null) {
            return self::$UPGRADE_UNSET;
        }

        return self::$UPGRADE_UNSET = new self('UPGRADE_UNSET', self::UPGRADE_UNSET_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    public static function INCREASE_ITEM_STORAGE()
    {
        if (self::$INCREASE_ITEM_STORAGE !== null) {
            return self::$INCREASE_ITEM_STORAGE;
        }

        return self::$INCREASE_ITEM_STORAGE = new self('INCREASE_ITEM_STORAGE', self::INCREASE_ITEM_STORAGE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    public static function INCREASE_POKEMON_STORAGE()
    {
        if (self::$INCREASE_POKEMON_STORAGE !== null) {
            return self::$INCREASE_POKEMON_STORAGE;
        }

        return self::$INCREASE_POKEMON_STORAGE = new self('INCREASE_POKEMON_STORAGE', self::INCREASE_POKEMON_STORAGE_VALUE);
    }

    /**
     * @param int $value
     * @return \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UPGRADE_UNSET();
            case 1: return self::INCREASE_ITEM_STORAGE();
            case 2: return self::INCREASE_POKEMON_STORAGE();
            default: return null;
        }
    }


}

