<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Enum.proto
 */


namespace PkgClient\Protocol\Enum;

/**
 * Protobuf enum : PkgClient.Protocol.Enum.PokemonId
 */
class PokemonId extends \Protobuf\Enum
{

    /**
     * MISSINGNO = 0
     */
    const MISSINGNO_VALUE = 0;

    /**
     * BULBASAUR = 1
     */
    const BULBASAUR_VALUE = 1;

    /**
     * IVYSAUR = 2
     */
    const IVYSAUR_VALUE = 2;

    /**
     * VENUSAUR = 3
     */
    const VENUSAUR_VALUE = 3;

    /**
     * CHARMENDER = 4
     */
    const CHARMENDER_VALUE = 4;

    /**
     * CHARMELEON = 5
     */
    const CHARMELEON_VALUE = 5;

    /**
     * CHARIZARD = 6
     */
    const CHARIZARD_VALUE = 6;

    /**
     * SQUIRTLE = 7
     */
    const SQUIRTLE_VALUE = 7;

    /**
     * WARTORTLE = 8
     */
    const WARTORTLE_VALUE = 8;

    /**
     * BLASTOISE = 9
     */
    const BLASTOISE_VALUE = 9;

    /**
     * CATERPIE = 10
     */
    const CATERPIE_VALUE = 10;

    /**
     * METAPOD = 11
     */
    const METAPOD_VALUE = 11;

    /**
     * BUTTERFREE = 12
     */
    const BUTTERFREE_VALUE = 12;

    /**
     * WEEDLE = 13
     */
    const WEEDLE_VALUE = 13;

    /**
     * KAKUNA = 14
     */
    const KAKUNA_VALUE = 14;

    /**
     * BEEDRILL = 15
     */
    const BEEDRILL_VALUE = 15;

    /**
     * PIDGEY = 16
     */
    const PIDGEY_VALUE = 16;

    /**
     * PIDGEOTTO = 17
     */
    const PIDGEOTTO_VALUE = 17;

    /**
     * PIDGEOT = 18
     */
    const PIDGEOT_VALUE = 18;

    /**
     * RATTATA = 19
     */
    const RATTATA_VALUE = 19;

    /**
     * RATICATE = 20
     */
    const RATICATE_VALUE = 20;

    /**
     * SPEAROW = 21
     */
    const SPEAROW_VALUE = 21;

    /**
     * FEAROW = 22
     */
    const FEAROW_VALUE = 22;

    /**
     * EKANS = 23
     */
    const EKANS_VALUE = 23;

    /**
     * ARBOK = 24
     */
    const ARBOK_VALUE = 24;

    /**
     * PIKACHU = 25
     */
    const PIKACHU_VALUE = 25;

    /**
     * RAICHU = 26
     */
    const RAICHU_VALUE = 26;

    /**
     * SANDSHREW = 27
     */
    const SANDSHREW_VALUE = 27;

    /**
     * SANDLASH = 28
     */
    const SANDLASH_VALUE = 28;

    /**
     * NIDORAN_FEMALE = 29
     */
    const NIDORAN_FEMALE_VALUE = 29;

    /**
     * NIDORINA = 30
     */
    const NIDORINA_VALUE = 30;

    /**
     * NIDOQUEEN = 31
     */
    const NIDOQUEEN_VALUE = 31;

    /**
     * NIDORAN_MALE = 32
     */
    const NIDORAN_MALE_VALUE = 32;

    /**
     * NIDORINO = 33
     */
    const NIDORINO_VALUE = 33;

    /**
     * NIDOKING = 34
     */
    const NIDOKING_VALUE = 34;

    /**
     * CLEFARY = 35
     */
    const CLEFARY_VALUE = 35;

    /**
     * CLEFABLE = 36
     */
    const CLEFABLE_VALUE = 36;

    /**
     * VULPIX = 37
     */
    const VULPIX_VALUE = 37;

    /**
     * NINETALES = 38
     */
    const NINETALES_VALUE = 38;

    /**
     * JIGGLYPUFF = 39
     */
    const JIGGLYPUFF_VALUE = 39;

    /**
     * WIGGLYTUFF = 40
     */
    const WIGGLYTUFF_VALUE = 40;

    /**
     * ZUBAT = 41
     */
    const ZUBAT_VALUE = 41;

    /**
     * GOLBAT = 42
     */
    const GOLBAT_VALUE = 42;

    /**
     * ODDISH = 43
     */
    const ODDISH_VALUE = 43;

    /**
     * GLOOM = 44
     */
    const GLOOM_VALUE = 44;

    /**
     * VILEPLUME = 45
     */
    const VILEPLUME_VALUE = 45;

    /**
     * PARAS = 46
     */
    const PARAS_VALUE = 46;

    /**
     * PARASECT = 47
     */
    const PARASECT_VALUE = 47;

    /**
     * VENONAT = 48
     */
    const VENONAT_VALUE = 48;

    /**
     * VENOMOTH = 49
     */
    const VENOMOTH_VALUE = 49;

    /**
     * DIGLETT = 50
     */
    const DIGLETT_VALUE = 50;

    /**
     * DUGTRIO = 51
     */
    const DUGTRIO_VALUE = 51;

    /**
     * MEOWTH = 52
     */
    const MEOWTH_VALUE = 52;

    /**
     * PERSIAN = 53
     */
    const PERSIAN_VALUE = 53;

    /**
     * PSYDUCK = 54
     */
    const PSYDUCK_VALUE = 54;

    /**
     * GOLDUCK = 55
     */
    const GOLDUCK_VALUE = 55;

    /**
     * MANKEY = 56
     */
    const MANKEY_VALUE = 56;

    /**
     * PRIMEAPE = 57
     */
    const PRIMEAPE_VALUE = 57;

    /**
     * GROWLITHE = 58
     */
    const GROWLITHE_VALUE = 58;

    /**
     * ARCANINE = 59
     */
    const ARCANINE_VALUE = 59;

    /**
     * POLIWAG = 60
     */
    const POLIWAG_VALUE = 60;

    /**
     * POLIWHIRL = 61
     */
    const POLIWHIRL_VALUE = 61;

    /**
     * POLIWRATH = 62
     */
    const POLIWRATH_VALUE = 62;

    /**
     * ABRA = 63
     */
    const ABRA_VALUE = 63;

    /**
     * KADABRA = 64
     */
    const KADABRA_VALUE = 64;

    /**
     * ALAKHAZAM = 65
     */
    const ALAKHAZAM_VALUE = 65;

    /**
     * MACHOP = 66
     */
    const MACHOP_VALUE = 66;

    /**
     * MACHOKE = 67
     */
    const MACHOKE_VALUE = 67;

    /**
     * MACHAMP = 68
     */
    const MACHAMP_VALUE = 68;

    /**
     * BELLSPROUT = 69
     */
    const BELLSPROUT_VALUE = 69;

    /**
     * WEEPINBELL = 70
     */
    const WEEPINBELL_VALUE = 70;

    /**
     * VICTREEBELL = 71
     */
    const VICTREEBELL_VALUE = 71;

    /**
     * TENTACOOL = 72
     */
    const TENTACOOL_VALUE = 72;

    /**
     * TENTACRUEL = 73
     */
    const TENTACRUEL_VALUE = 73;

    /**
     * GEODUGE = 74
     */
    const GEODUGE_VALUE = 74;

    /**
     * GRAVELER = 75
     */
    const GRAVELER_VALUE = 75;

    /**
     * GOLEM = 76
     */
    const GOLEM_VALUE = 76;

    /**
     * PONYTA = 77
     */
    const PONYTA_VALUE = 77;

    /**
     * RAPIDASH = 78
     */
    const RAPIDASH_VALUE = 78;

    /**
     * SLOWPOKE = 79
     */
    const SLOWPOKE_VALUE = 79;

    /**
     * SLOWBRO = 80
     */
    const SLOWBRO_VALUE = 80;

    /**
     * MAGNEMITE = 81
     */
    const MAGNEMITE_VALUE = 81;

    /**
     * MAGNETON = 82
     */
    const MAGNETON_VALUE = 82;

    /**
     * FARFETCHD = 83
     */
    const FARFETCHD_VALUE = 83;

    /**
     * DODUO = 84
     */
    const DODUO_VALUE = 84;

    /**
     * DODRIO = 85
     */
    const DODRIO_VALUE = 85;

    /**
     * SEEL = 86
     */
    const SEEL_VALUE = 86;

    /**
     * DEWGONG = 87
     */
    const DEWGONG_VALUE = 87;

    /**
     * GRIMER = 88
     */
    const GRIMER_VALUE = 88;

    /**
     * MUK = 89
     */
    const MUK_VALUE = 89;

    /**
     * SHELLDER = 90
     */
    const SHELLDER_VALUE = 90;

    /**
     * CLOYSTER = 91
     */
    const CLOYSTER_VALUE = 91;

    /**
     * GASTLY = 92
     */
    const GASTLY_VALUE = 92;

    /**
     * HAUNTER = 93
     */
    const HAUNTER_VALUE = 93;

    /**
     * GENGAR = 94
     */
    const GENGAR_VALUE = 94;

    /**
     * ONIX = 95
     */
    const ONIX_VALUE = 95;

    /**
     * DROWZEE = 96
     */
    const DROWZEE_VALUE = 96;

    /**
     * HYPNO = 97
     */
    const HYPNO_VALUE = 97;

    /**
     * KRABBY = 98
     */
    const KRABBY_VALUE = 98;

    /**
     * KINGLER = 99
     */
    const KINGLER_VALUE = 99;

    /**
     * VOLTORB = 100
     */
    const VOLTORB_VALUE = 100;

    /**
     * ELECTRODE = 101
     */
    const ELECTRODE_VALUE = 101;

    /**
     * EXEGGCUTE = 102
     */
    const EXEGGCUTE_VALUE = 102;

    /**
     * EXEGGUTOR = 103
     */
    const EXEGGUTOR_VALUE = 103;

    /**
     * CUBONE = 104
     */
    const CUBONE_VALUE = 104;

    /**
     * MAROWAK = 105
     */
    const MAROWAK_VALUE = 105;

    /**
     * HITMONLEE = 106
     */
    const HITMONLEE_VALUE = 106;

    /**
     * HITMONCHAN = 107
     */
    const HITMONCHAN_VALUE = 107;

    /**
     * LICKITUNG = 108
     */
    const LICKITUNG_VALUE = 108;

    /**
     * KOFFING = 109
     */
    const KOFFING_VALUE = 109;

    /**
     * WEEZING = 110
     */
    const WEEZING_VALUE = 110;

    /**
     * RHYHORN = 111
     */
    const RHYHORN_VALUE = 111;

    /**
     * RHYDON = 112
     */
    const RHYDON_VALUE = 112;

    /**
     * CHANSEY = 113
     */
    const CHANSEY_VALUE = 113;

    /**
     * TANGELA = 114
     */
    const TANGELA_VALUE = 114;

    /**
     * KANGASKHAN = 115
     */
    const KANGASKHAN_VALUE = 115;

    /**
     * HORSEA = 116
     */
    const HORSEA_VALUE = 116;

    /**
     * SEADRA = 117
     */
    const SEADRA_VALUE = 117;

    /**
     * GOLDEEN = 118
     */
    const GOLDEEN_VALUE = 118;

    /**
     * SEAKING = 119
     */
    const SEAKING_VALUE = 119;

    /**
     * STARYU = 120
     */
    const STARYU_VALUE = 120;

    /**
     * STARMIE = 121
     */
    const STARMIE_VALUE = 121;

    /**
     * MR_MIME = 122
     */
    const MR_MIME_VALUE = 122;

    /**
     * SCYTHER = 123
     */
    const SCYTHER_VALUE = 123;

    /**
     * JYNX = 124
     */
    const JYNX_VALUE = 124;

    /**
     * ELECTABUZZ = 125
     */
    const ELECTABUZZ_VALUE = 125;

    /**
     * MAGMAR = 126
     */
    const MAGMAR_VALUE = 126;

    /**
     * PINSIR = 127
     */
    const PINSIR_VALUE = 127;

    /**
     * TAUROS = 128
     */
    const TAUROS_VALUE = 128;

    /**
     * MAGIKARP = 129
     */
    const MAGIKARP_VALUE = 129;

    /**
     * GYARADOS = 130
     */
    const GYARADOS_VALUE = 130;

    /**
     * LAPRAS = 131
     */
    const LAPRAS_VALUE = 131;

    /**
     * DITTO = 132
     */
    const DITTO_VALUE = 132;

    /**
     * EEVEE = 133
     */
    const EEVEE_VALUE = 133;

    /**
     * VAPOREON = 134
     */
    const VAPOREON_VALUE = 134;

    /**
     * JOLTEON = 135
     */
    const JOLTEON_VALUE = 135;

    /**
     * FLAREON = 136
     */
    const FLAREON_VALUE = 136;

    /**
     * PORYGON = 137
     */
    const PORYGON_VALUE = 137;

    /**
     * OMANYTE = 138
     */
    const OMANYTE_VALUE = 138;

    /**
     * OMASTAR = 139
     */
    const OMASTAR_VALUE = 139;

    /**
     * KABUTO = 140
     */
    const KABUTO_VALUE = 140;

    /**
     * KABUTOPS = 141
     */
    const KABUTOPS_VALUE = 141;

    /**
     * AERODACTYL = 142
     */
    const AERODACTYL_VALUE = 142;

    /**
     * SNORLAX = 143
     */
    const SNORLAX_VALUE = 143;

    /**
     * ARTICUNO = 144
     */
    const ARTICUNO_VALUE = 144;

    /**
     * ZAPDOS = 145
     */
    const ZAPDOS_VALUE = 145;

    /**
     * MOLTRES = 146
     */
    const MOLTRES_VALUE = 146;

    /**
     * DRATINI = 147
     */
    const DRATINI_VALUE = 147;

    /**
     * DRAGONAIR = 148
     */
    const DRAGONAIR_VALUE = 148;

    /**
     * DRAGONITE = 149
     */
    const DRAGONITE_VALUE = 149;

    /**
     * MEWTWO = 150
     */
    const MEWTWO_VALUE = 150;

    /**
     * MEW = 151
     */
    const MEW_VALUE = 151;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MISSINGNO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $BULBASAUR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $IVYSAUR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VENUSAUR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CHARMENDER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CHARMELEON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CHARIZARD = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SQUIRTLE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $WARTORTLE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $BLASTOISE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CATERPIE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $METAPOD = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $BUTTERFREE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $WEEDLE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KAKUNA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $BEEDRILL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PIDGEY = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PIDGEOTTO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PIDGEOT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $RATTATA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $RATICATE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SPEAROW = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $FEAROW = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $EKANS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ARBOK = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PIKACHU = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $RAICHU = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SANDSHREW = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SANDLASH = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NIDORAN_FEMALE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NIDORINA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NIDOQUEEN = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NIDORAN_MALE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NIDORINO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NIDOKING = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CLEFARY = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CLEFABLE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VULPIX = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $NINETALES = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $JIGGLYPUFF = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $WIGGLYTUFF = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ZUBAT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GOLBAT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ODDISH = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GLOOM = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VILEPLUME = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PARAS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PARASECT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VENONAT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VENOMOTH = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DIGLETT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DUGTRIO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MEOWTH = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PERSIAN = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PSYDUCK = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GOLDUCK = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MANKEY = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PRIMEAPE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GROWLITHE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ARCANINE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $POLIWAG = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $POLIWHIRL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $POLIWRATH = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ABRA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KADABRA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ALAKHAZAM = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MACHOP = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MACHOKE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MACHAMP = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $BELLSPROUT = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $WEEPINBELL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VICTREEBELL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $TENTACOOL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $TENTACRUEL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GEODUGE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GRAVELER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GOLEM = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PONYTA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $RAPIDASH = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SLOWPOKE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SLOWBRO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MAGNEMITE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MAGNETON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $FARFETCHD = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DODUO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DODRIO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SEEL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DEWGONG = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GRIMER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MUK = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SHELLDER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CLOYSTER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GASTLY = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $HAUNTER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GENGAR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ONIX = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DROWZEE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $HYPNO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KRABBY = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KINGLER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VOLTORB = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ELECTRODE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $EXEGGCUTE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $EXEGGUTOR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CUBONE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MAROWAK = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $HITMONLEE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $HITMONCHAN = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $LICKITUNG = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KOFFING = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $WEEZING = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $RHYHORN = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $RHYDON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $CHANSEY = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $TANGELA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KANGASKHAN = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $HORSEA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SEADRA = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GOLDEEN = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SEAKING = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $STARYU = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $STARMIE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MR_MIME = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SCYTHER = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $JYNX = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ELECTABUZZ = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MAGMAR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PINSIR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $TAUROS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MAGIKARP = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $GYARADOS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $LAPRAS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DITTO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $EEVEE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $VAPOREON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $JOLTEON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $FLAREON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $PORYGON = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $OMANYTE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $OMASTAR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KABUTO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $KABUTOPS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $AERODACTYL = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $SNORLAX = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ARTICUNO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $ZAPDOS = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MOLTRES = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DRATINI = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DRAGONAIR = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $DRAGONITE = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MEWTWO = null;

    /**
     * @var \PkgClient\Protocol\Enum\PokemonId
     */
    protected static $MEW = null;

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MISSINGNO()
    {
        if (self::$MISSINGNO !== null) {
            return self::$MISSINGNO;
        }

        return self::$MISSINGNO = new self('MISSINGNO', self::MISSINGNO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function BULBASAUR()
    {
        if (self::$BULBASAUR !== null) {
            return self::$BULBASAUR;
        }

        return self::$BULBASAUR = new self('BULBASAUR', self::BULBASAUR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function IVYSAUR()
    {
        if (self::$IVYSAUR !== null) {
            return self::$IVYSAUR;
        }

        return self::$IVYSAUR = new self('IVYSAUR', self::IVYSAUR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VENUSAUR()
    {
        if (self::$VENUSAUR !== null) {
            return self::$VENUSAUR;
        }

        return self::$VENUSAUR = new self('VENUSAUR', self::VENUSAUR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CHARMENDER()
    {
        if (self::$CHARMENDER !== null) {
            return self::$CHARMENDER;
        }

        return self::$CHARMENDER = new self('CHARMENDER', self::CHARMENDER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CHARMELEON()
    {
        if (self::$CHARMELEON !== null) {
            return self::$CHARMELEON;
        }

        return self::$CHARMELEON = new self('CHARMELEON', self::CHARMELEON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CHARIZARD()
    {
        if (self::$CHARIZARD !== null) {
            return self::$CHARIZARD;
        }

        return self::$CHARIZARD = new self('CHARIZARD', self::CHARIZARD_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SQUIRTLE()
    {
        if (self::$SQUIRTLE !== null) {
            return self::$SQUIRTLE;
        }

        return self::$SQUIRTLE = new self('SQUIRTLE', self::SQUIRTLE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function WARTORTLE()
    {
        if (self::$WARTORTLE !== null) {
            return self::$WARTORTLE;
        }

        return self::$WARTORTLE = new self('WARTORTLE', self::WARTORTLE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function BLASTOISE()
    {
        if (self::$BLASTOISE !== null) {
            return self::$BLASTOISE;
        }

        return self::$BLASTOISE = new self('BLASTOISE', self::BLASTOISE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CATERPIE()
    {
        if (self::$CATERPIE !== null) {
            return self::$CATERPIE;
        }

        return self::$CATERPIE = new self('CATERPIE', self::CATERPIE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function METAPOD()
    {
        if (self::$METAPOD !== null) {
            return self::$METAPOD;
        }

        return self::$METAPOD = new self('METAPOD', self::METAPOD_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function BUTTERFREE()
    {
        if (self::$BUTTERFREE !== null) {
            return self::$BUTTERFREE;
        }

        return self::$BUTTERFREE = new self('BUTTERFREE', self::BUTTERFREE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function WEEDLE()
    {
        if (self::$WEEDLE !== null) {
            return self::$WEEDLE;
        }

        return self::$WEEDLE = new self('WEEDLE', self::WEEDLE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KAKUNA()
    {
        if (self::$KAKUNA !== null) {
            return self::$KAKUNA;
        }

        return self::$KAKUNA = new self('KAKUNA', self::KAKUNA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function BEEDRILL()
    {
        if (self::$BEEDRILL !== null) {
            return self::$BEEDRILL;
        }

        return self::$BEEDRILL = new self('BEEDRILL', self::BEEDRILL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PIDGEY()
    {
        if (self::$PIDGEY !== null) {
            return self::$PIDGEY;
        }

        return self::$PIDGEY = new self('PIDGEY', self::PIDGEY_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PIDGEOTTO()
    {
        if (self::$PIDGEOTTO !== null) {
            return self::$PIDGEOTTO;
        }

        return self::$PIDGEOTTO = new self('PIDGEOTTO', self::PIDGEOTTO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PIDGEOT()
    {
        if (self::$PIDGEOT !== null) {
            return self::$PIDGEOT;
        }

        return self::$PIDGEOT = new self('PIDGEOT', self::PIDGEOT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function RATTATA()
    {
        if (self::$RATTATA !== null) {
            return self::$RATTATA;
        }

        return self::$RATTATA = new self('RATTATA', self::RATTATA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function RATICATE()
    {
        if (self::$RATICATE !== null) {
            return self::$RATICATE;
        }

        return self::$RATICATE = new self('RATICATE', self::RATICATE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SPEAROW()
    {
        if (self::$SPEAROW !== null) {
            return self::$SPEAROW;
        }

        return self::$SPEAROW = new self('SPEAROW', self::SPEAROW_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function FEAROW()
    {
        if (self::$FEAROW !== null) {
            return self::$FEAROW;
        }

        return self::$FEAROW = new self('FEAROW', self::FEAROW_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function EKANS()
    {
        if (self::$EKANS !== null) {
            return self::$EKANS;
        }

        return self::$EKANS = new self('EKANS', self::EKANS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ARBOK()
    {
        if (self::$ARBOK !== null) {
            return self::$ARBOK;
        }

        return self::$ARBOK = new self('ARBOK', self::ARBOK_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PIKACHU()
    {
        if (self::$PIKACHU !== null) {
            return self::$PIKACHU;
        }

        return self::$PIKACHU = new self('PIKACHU', self::PIKACHU_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function RAICHU()
    {
        if (self::$RAICHU !== null) {
            return self::$RAICHU;
        }

        return self::$RAICHU = new self('RAICHU', self::RAICHU_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SANDSHREW()
    {
        if (self::$SANDSHREW !== null) {
            return self::$SANDSHREW;
        }

        return self::$SANDSHREW = new self('SANDSHREW', self::SANDSHREW_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SANDLASH()
    {
        if (self::$SANDLASH !== null) {
            return self::$SANDLASH;
        }

        return self::$SANDLASH = new self('SANDLASH', self::SANDLASH_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NIDORAN_FEMALE()
    {
        if (self::$NIDORAN_FEMALE !== null) {
            return self::$NIDORAN_FEMALE;
        }

        return self::$NIDORAN_FEMALE = new self('NIDORAN_FEMALE', self::NIDORAN_FEMALE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NIDORINA()
    {
        if (self::$NIDORINA !== null) {
            return self::$NIDORINA;
        }

        return self::$NIDORINA = new self('NIDORINA', self::NIDORINA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NIDOQUEEN()
    {
        if (self::$NIDOQUEEN !== null) {
            return self::$NIDOQUEEN;
        }

        return self::$NIDOQUEEN = new self('NIDOQUEEN', self::NIDOQUEEN_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NIDORAN_MALE()
    {
        if (self::$NIDORAN_MALE !== null) {
            return self::$NIDORAN_MALE;
        }

        return self::$NIDORAN_MALE = new self('NIDORAN_MALE', self::NIDORAN_MALE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NIDORINO()
    {
        if (self::$NIDORINO !== null) {
            return self::$NIDORINO;
        }

        return self::$NIDORINO = new self('NIDORINO', self::NIDORINO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NIDOKING()
    {
        if (self::$NIDOKING !== null) {
            return self::$NIDOKING;
        }

        return self::$NIDOKING = new self('NIDOKING', self::NIDOKING_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CLEFARY()
    {
        if (self::$CLEFARY !== null) {
            return self::$CLEFARY;
        }

        return self::$CLEFARY = new self('CLEFARY', self::CLEFARY_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CLEFABLE()
    {
        if (self::$CLEFABLE !== null) {
            return self::$CLEFABLE;
        }

        return self::$CLEFABLE = new self('CLEFABLE', self::CLEFABLE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VULPIX()
    {
        if (self::$VULPIX !== null) {
            return self::$VULPIX;
        }

        return self::$VULPIX = new self('VULPIX', self::VULPIX_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function NINETALES()
    {
        if (self::$NINETALES !== null) {
            return self::$NINETALES;
        }

        return self::$NINETALES = new self('NINETALES', self::NINETALES_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function JIGGLYPUFF()
    {
        if (self::$JIGGLYPUFF !== null) {
            return self::$JIGGLYPUFF;
        }

        return self::$JIGGLYPUFF = new self('JIGGLYPUFF', self::JIGGLYPUFF_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function WIGGLYTUFF()
    {
        if (self::$WIGGLYTUFF !== null) {
            return self::$WIGGLYTUFF;
        }

        return self::$WIGGLYTUFF = new self('WIGGLYTUFF', self::WIGGLYTUFF_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ZUBAT()
    {
        if (self::$ZUBAT !== null) {
            return self::$ZUBAT;
        }

        return self::$ZUBAT = new self('ZUBAT', self::ZUBAT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GOLBAT()
    {
        if (self::$GOLBAT !== null) {
            return self::$GOLBAT;
        }

        return self::$GOLBAT = new self('GOLBAT', self::GOLBAT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ODDISH()
    {
        if (self::$ODDISH !== null) {
            return self::$ODDISH;
        }

        return self::$ODDISH = new self('ODDISH', self::ODDISH_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GLOOM()
    {
        if (self::$GLOOM !== null) {
            return self::$GLOOM;
        }

        return self::$GLOOM = new self('GLOOM', self::GLOOM_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VILEPLUME()
    {
        if (self::$VILEPLUME !== null) {
            return self::$VILEPLUME;
        }

        return self::$VILEPLUME = new self('VILEPLUME', self::VILEPLUME_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PARAS()
    {
        if (self::$PARAS !== null) {
            return self::$PARAS;
        }

        return self::$PARAS = new self('PARAS', self::PARAS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PARASECT()
    {
        if (self::$PARASECT !== null) {
            return self::$PARASECT;
        }

        return self::$PARASECT = new self('PARASECT', self::PARASECT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VENONAT()
    {
        if (self::$VENONAT !== null) {
            return self::$VENONAT;
        }

        return self::$VENONAT = new self('VENONAT', self::VENONAT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VENOMOTH()
    {
        if (self::$VENOMOTH !== null) {
            return self::$VENOMOTH;
        }

        return self::$VENOMOTH = new self('VENOMOTH', self::VENOMOTH_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DIGLETT()
    {
        if (self::$DIGLETT !== null) {
            return self::$DIGLETT;
        }

        return self::$DIGLETT = new self('DIGLETT', self::DIGLETT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DUGTRIO()
    {
        if (self::$DUGTRIO !== null) {
            return self::$DUGTRIO;
        }

        return self::$DUGTRIO = new self('DUGTRIO', self::DUGTRIO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MEOWTH()
    {
        if (self::$MEOWTH !== null) {
            return self::$MEOWTH;
        }

        return self::$MEOWTH = new self('MEOWTH', self::MEOWTH_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PERSIAN()
    {
        if (self::$PERSIAN !== null) {
            return self::$PERSIAN;
        }

        return self::$PERSIAN = new self('PERSIAN', self::PERSIAN_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PSYDUCK()
    {
        if (self::$PSYDUCK !== null) {
            return self::$PSYDUCK;
        }

        return self::$PSYDUCK = new self('PSYDUCK', self::PSYDUCK_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GOLDUCK()
    {
        if (self::$GOLDUCK !== null) {
            return self::$GOLDUCK;
        }

        return self::$GOLDUCK = new self('GOLDUCK', self::GOLDUCK_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MANKEY()
    {
        if (self::$MANKEY !== null) {
            return self::$MANKEY;
        }

        return self::$MANKEY = new self('MANKEY', self::MANKEY_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PRIMEAPE()
    {
        if (self::$PRIMEAPE !== null) {
            return self::$PRIMEAPE;
        }

        return self::$PRIMEAPE = new self('PRIMEAPE', self::PRIMEAPE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GROWLITHE()
    {
        if (self::$GROWLITHE !== null) {
            return self::$GROWLITHE;
        }

        return self::$GROWLITHE = new self('GROWLITHE', self::GROWLITHE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ARCANINE()
    {
        if (self::$ARCANINE !== null) {
            return self::$ARCANINE;
        }

        return self::$ARCANINE = new self('ARCANINE', self::ARCANINE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function POLIWAG()
    {
        if (self::$POLIWAG !== null) {
            return self::$POLIWAG;
        }

        return self::$POLIWAG = new self('POLIWAG', self::POLIWAG_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function POLIWHIRL()
    {
        if (self::$POLIWHIRL !== null) {
            return self::$POLIWHIRL;
        }

        return self::$POLIWHIRL = new self('POLIWHIRL', self::POLIWHIRL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function POLIWRATH()
    {
        if (self::$POLIWRATH !== null) {
            return self::$POLIWRATH;
        }

        return self::$POLIWRATH = new self('POLIWRATH', self::POLIWRATH_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ABRA()
    {
        if (self::$ABRA !== null) {
            return self::$ABRA;
        }

        return self::$ABRA = new self('ABRA', self::ABRA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KADABRA()
    {
        if (self::$KADABRA !== null) {
            return self::$KADABRA;
        }

        return self::$KADABRA = new self('KADABRA', self::KADABRA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ALAKHAZAM()
    {
        if (self::$ALAKHAZAM !== null) {
            return self::$ALAKHAZAM;
        }

        return self::$ALAKHAZAM = new self('ALAKHAZAM', self::ALAKHAZAM_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MACHOP()
    {
        if (self::$MACHOP !== null) {
            return self::$MACHOP;
        }

        return self::$MACHOP = new self('MACHOP', self::MACHOP_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MACHOKE()
    {
        if (self::$MACHOKE !== null) {
            return self::$MACHOKE;
        }

        return self::$MACHOKE = new self('MACHOKE', self::MACHOKE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MACHAMP()
    {
        if (self::$MACHAMP !== null) {
            return self::$MACHAMP;
        }

        return self::$MACHAMP = new self('MACHAMP', self::MACHAMP_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function BELLSPROUT()
    {
        if (self::$BELLSPROUT !== null) {
            return self::$BELLSPROUT;
        }

        return self::$BELLSPROUT = new self('BELLSPROUT', self::BELLSPROUT_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function WEEPINBELL()
    {
        if (self::$WEEPINBELL !== null) {
            return self::$WEEPINBELL;
        }

        return self::$WEEPINBELL = new self('WEEPINBELL', self::WEEPINBELL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VICTREEBELL()
    {
        if (self::$VICTREEBELL !== null) {
            return self::$VICTREEBELL;
        }

        return self::$VICTREEBELL = new self('VICTREEBELL', self::VICTREEBELL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function TENTACOOL()
    {
        if (self::$TENTACOOL !== null) {
            return self::$TENTACOOL;
        }

        return self::$TENTACOOL = new self('TENTACOOL', self::TENTACOOL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function TENTACRUEL()
    {
        if (self::$TENTACRUEL !== null) {
            return self::$TENTACRUEL;
        }

        return self::$TENTACRUEL = new self('TENTACRUEL', self::TENTACRUEL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GEODUGE()
    {
        if (self::$GEODUGE !== null) {
            return self::$GEODUGE;
        }

        return self::$GEODUGE = new self('GEODUGE', self::GEODUGE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GRAVELER()
    {
        if (self::$GRAVELER !== null) {
            return self::$GRAVELER;
        }

        return self::$GRAVELER = new self('GRAVELER', self::GRAVELER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GOLEM()
    {
        if (self::$GOLEM !== null) {
            return self::$GOLEM;
        }

        return self::$GOLEM = new self('GOLEM', self::GOLEM_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PONYTA()
    {
        if (self::$PONYTA !== null) {
            return self::$PONYTA;
        }

        return self::$PONYTA = new self('PONYTA', self::PONYTA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function RAPIDASH()
    {
        if (self::$RAPIDASH !== null) {
            return self::$RAPIDASH;
        }

        return self::$RAPIDASH = new self('RAPIDASH', self::RAPIDASH_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SLOWPOKE()
    {
        if (self::$SLOWPOKE !== null) {
            return self::$SLOWPOKE;
        }

        return self::$SLOWPOKE = new self('SLOWPOKE', self::SLOWPOKE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SLOWBRO()
    {
        if (self::$SLOWBRO !== null) {
            return self::$SLOWBRO;
        }

        return self::$SLOWBRO = new self('SLOWBRO', self::SLOWBRO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MAGNEMITE()
    {
        if (self::$MAGNEMITE !== null) {
            return self::$MAGNEMITE;
        }

        return self::$MAGNEMITE = new self('MAGNEMITE', self::MAGNEMITE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MAGNETON()
    {
        if (self::$MAGNETON !== null) {
            return self::$MAGNETON;
        }

        return self::$MAGNETON = new self('MAGNETON', self::MAGNETON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function FARFETCHD()
    {
        if (self::$FARFETCHD !== null) {
            return self::$FARFETCHD;
        }

        return self::$FARFETCHD = new self('FARFETCHD', self::FARFETCHD_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DODUO()
    {
        if (self::$DODUO !== null) {
            return self::$DODUO;
        }

        return self::$DODUO = new self('DODUO', self::DODUO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DODRIO()
    {
        if (self::$DODRIO !== null) {
            return self::$DODRIO;
        }

        return self::$DODRIO = new self('DODRIO', self::DODRIO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SEEL()
    {
        if (self::$SEEL !== null) {
            return self::$SEEL;
        }

        return self::$SEEL = new self('SEEL', self::SEEL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DEWGONG()
    {
        if (self::$DEWGONG !== null) {
            return self::$DEWGONG;
        }

        return self::$DEWGONG = new self('DEWGONG', self::DEWGONG_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GRIMER()
    {
        if (self::$GRIMER !== null) {
            return self::$GRIMER;
        }

        return self::$GRIMER = new self('GRIMER', self::GRIMER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MUK()
    {
        if (self::$MUK !== null) {
            return self::$MUK;
        }

        return self::$MUK = new self('MUK', self::MUK_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SHELLDER()
    {
        if (self::$SHELLDER !== null) {
            return self::$SHELLDER;
        }

        return self::$SHELLDER = new self('SHELLDER', self::SHELLDER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CLOYSTER()
    {
        if (self::$CLOYSTER !== null) {
            return self::$CLOYSTER;
        }

        return self::$CLOYSTER = new self('CLOYSTER', self::CLOYSTER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GASTLY()
    {
        if (self::$GASTLY !== null) {
            return self::$GASTLY;
        }

        return self::$GASTLY = new self('GASTLY', self::GASTLY_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function HAUNTER()
    {
        if (self::$HAUNTER !== null) {
            return self::$HAUNTER;
        }

        return self::$HAUNTER = new self('HAUNTER', self::HAUNTER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GENGAR()
    {
        if (self::$GENGAR !== null) {
            return self::$GENGAR;
        }

        return self::$GENGAR = new self('GENGAR', self::GENGAR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ONIX()
    {
        if (self::$ONIX !== null) {
            return self::$ONIX;
        }

        return self::$ONIX = new self('ONIX', self::ONIX_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DROWZEE()
    {
        if (self::$DROWZEE !== null) {
            return self::$DROWZEE;
        }

        return self::$DROWZEE = new self('DROWZEE', self::DROWZEE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function HYPNO()
    {
        if (self::$HYPNO !== null) {
            return self::$HYPNO;
        }

        return self::$HYPNO = new self('HYPNO', self::HYPNO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KRABBY()
    {
        if (self::$KRABBY !== null) {
            return self::$KRABBY;
        }

        return self::$KRABBY = new self('KRABBY', self::KRABBY_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KINGLER()
    {
        if (self::$KINGLER !== null) {
            return self::$KINGLER;
        }

        return self::$KINGLER = new self('KINGLER', self::KINGLER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VOLTORB()
    {
        if (self::$VOLTORB !== null) {
            return self::$VOLTORB;
        }

        return self::$VOLTORB = new self('VOLTORB', self::VOLTORB_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ELECTRODE()
    {
        if (self::$ELECTRODE !== null) {
            return self::$ELECTRODE;
        }

        return self::$ELECTRODE = new self('ELECTRODE', self::ELECTRODE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function EXEGGCUTE()
    {
        if (self::$EXEGGCUTE !== null) {
            return self::$EXEGGCUTE;
        }

        return self::$EXEGGCUTE = new self('EXEGGCUTE', self::EXEGGCUTE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function EXEGGUTOR()
    {
        if (self::$EXEGGUTOR !== null) {
            return self::$EXEGGUTOR;
        }

        return self::$EXEGGUTOR = new self('EXEGGUTOR', self::EXEGGUTOR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CUBONE()
    {
        if (self::$CUBONE !== null) {
            return self::$CUBONE;
        }

        return self::$CUBONE = new self('CUBONE', self::CUBONE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MAROWAK()
    {
        if (self::$MAROWAK !== null) {
            return self::$MAROWAK;
        }

        return self::$MAROWAK = new self('MAROWAK', self::MAROWAK_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function HITMONLEE()
    {
        if (self::$HITMONLEE !== null) {
            return self::$HITMONLEE;
        }

        return self::$HITMONLEE = new self('HITMONLEE', self::HITMONLEE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function HITMONCHAN()
    {
        if (self::$HITMONCHAN !== null) {
            return self::$HITMONCHAN;
        }

        return self::$HITMONCHAN = new self('HITMONCHAN', self::HITMONCHAN_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function LICKITUNG()
    {
        if (self::$LICKITUNG !== null) {
            return self::$LICKITUNG;
        }

        return self::$LICKITUNG = new self('LICKITUNG', self::LICKITUNG_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KOFFING()
    {
        if (self::$KOFFING !== null) {
            return self::$KOFFING;
        }

        return self::$KOFFING = new self('KOFFING', self::KOFFING_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function WEEZING()
    {
        if (self::$WEEZING !== null) {
            return self::$WEEZING;
        }

        return self::$WEEZING = new self('WEEZING', self::WEEZING_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function RHYHORN()
    {
        if (self::$RHYHORN !== null) {
            return self::$RHYHORN;
        }

        return self::$RHYHORN = new self('RHYHORN', self::RHYHORN_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function RHYDON()
    {
        if (self::$RHYDON !== null) {
            return self::$RHYDON;
        }

        return self::$RHYDON = new self('RHYDON', self::RHYDON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function CHANSEY()
    {
        if (self::$CHANSEY !== null) {
            return self::$CHANSEY;
        }

        return self::$CHANSEY = new self('CHANSEY', self::CHANSEY_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function TANGELA()
    {
        if (self::$TANGELA !== null) {
            return self::$TANGELA;
        }

        return self::$TANGELA = new self('TANGELA', self::TANGELA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KANGASKHAN()
    {
        if (self::$KANGASKHAN !== null) {
            return self::$KANGASKHAN;
        }

        return self::$KANGASKHAN = new self('KANGASKHAN', self::KANGASKHAN_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function HORSEA()
    {
        if (self::$HORSEA !== null) {
            return self::$HORSEA;
        }

        return self::$HORSEA = new self('HORSEA', self::HORSEA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SEADRA()
    {
        if (self::$SEADRA !== null) {
            return self::$SEADRA;
        }

        return self::$SEADRA = new self('SEADRA', self::SEADRA_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GOLDEEN()
    {
        if (self::$GOLDEEN !== null) {
            return self::$GOLDEEN;
        }

        return self::$GOLDEEN = new self('GOLDEEN', self::GOLDEEN_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SEAKING()
    {
        if (self::$SEAKING !== null) {
            return self::$SEAKING;
        }

        return self::$SEAKING = new self('SEAKING', self::SEAKING_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function STARYU()
    {
        if (self::$STARYU !== null) {
            return self::$STARYU;
        }

        return self::$STARYU = new self('STARYU', self::STARYU_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function STARMIE()
    {
        if (self::$STARMIE !== null) {
            return self::$STARMIE;
        }

        return self::$STARMIE = new self('STARMIE', self::STARMIE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MR_MIME()
    {
        if (self::$MR_MIME !== null) {
            return self::$MR_MIME;
        }

        return self::$MR_MIME = new self('MR_MIME', self::MR_MIME_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SCYTHER()
    {
        if (self::$SCYTHER !== null) {
            return self::$SCYTHER;
        }

        return self::$SCYTHER = new self('SCYTHER', self::SCYTHER_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function JYNX()
    {
        if (self::$JYNX !== null) {
            return self::$JYNX;
        }

        return self::$JYNX = new self('JYNX', self::JYNX_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ELECTABUZZ()
    {
        if (self::$ELECTABUZZ !== null) {
            return self::$ELECTABUZZ;
        }

        return self::$ELECTABUZZ = new self('ELECTABUZZ', self::ELECTABUZZ_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MAGMAR()
    {
        if (self::$MAGMAR !== null) {
            return self::$MAGMAR;
        }

        return self::$MAGMAR = new self('MAGMAR', self::MAGMAR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PINSIR()
    {
        if (self::$PINSIR !== null) {
            return self::$PINSIR;
        }

        return self::$PINSIR = new self('PINSIR', self::PINSIR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function TAUROS()
    {
        if (self::$TAUROS !== null) {
            return self::$TAUROS;
        }

        return self::$TAUROS = new self('TAUROS', self::TAUROS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MAGIKARP()
    {
        if (self::$MAGIKARP !== null) {
            return self::$MAGIKARP;
        }

        return self::$MAGIKARP = new self('MAGIKARP', self::MAGIKARP_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function GYARADOS()
    {
        if (self::$GYARADOS !== null) {
            return self::$GYARADOS;
        }

        return self::$GYARADOS = new self('GYARADOS', self::GYARADOS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function LAPRAS()
    {
        if (self::$LAPRAS !== null) {
            return self::$LAPRAS;
        }

        return self::$LAPRAS = new self('LAPRAS', self::LAPRAS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DITTO()
    {
        if (self::$DITTO !== null) {
            return self::$DITTO;
        }

        return self::$DITTO = new self('DITTO', self::DITTO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function EEVEE()
    {
        if (self::$EEVEE !== null) {
            return self::$EEVEE;
        }

        return self::$EEVEE = new self('EEVEE', self::EEVEE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function VAPOREON()
    {
        if (self::$VAPOREON !== null) {
            return self::$VAPOREON;
        }

        return self::$VAPOREON = new self('VAPOREON', self::VAPOREON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function JOLTEON()
    {
        if (self::$JOLTEON !== null) {
            return self::$JOLTEON;
        }

        return self::$JOLTEON = new self('JOLTEON', self::JOLTEON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function FLAREON()
    {
        if (self::$FLAREON !== null) {
            return self::$FLAREON;
        }

        return self::$FLAREON = new self('FLAREON', self::FLAREON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function PORYGON()
    {
        if (self::$PORYGON !== null) {
            return self::$PORYGON;
        }

        return self::$PORYGON = new self('PORYGON', self::PORYGON_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function OMANYTE()
    {
        if (self::$OMANYTE !== null) {
            return self::$OMANYTE;
        }

        return self::$OMANYTE = new self('OMANYTE', self::OMANYTE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function OMASTAR()
    {
        if (self::$OMASTAR !== null) {
            return self::$OMASTAR;
        }

        return self::$OMASTAR = new self('OMASTAR', self::OMASTAR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KABUTO()
    {
        if (self::$KABUTO !== null) {
            return self::$KABUTO;
        }

        return self::$KABUTO = new self('KABUTO', self::KABUTO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function KABUTOPS()
    {
        if (self::$KABUTOPS !== null) {
            return self::$KABUTOPS;
        }

        return self::$KABUTOPS = new self('KABUTOPS', self::KABUTOPS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function AERODACTYL()
    {
        if (self::$AERODACTYL !== null) {
            return self::$AERODACTYL;
        }

        return self::$AERODACTYL = new self('AERODACTYL', self::AERODACTYL_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function SNORLAX()
    {
        if (self::$SNORLAX !== null) {
            return self::$SNORLAX;
        }

        return self::$SNORLAX = new self('SNORLAX', self::SNORLAX_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ARTICUNO()
    {
        if (self::$ARTICUNO !== null) {
            return self::$ARTICUNO;
        }

        return self::$ARTICUNO = new self('ARTICUNO', self::ARTICUNO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function ZAPDOS()
    {
        if (self::$ZAPDOS !== null) {
            return self::$ZAPDOS;
        }

        return self::$ZAPDOS = new self('ZAPDOS', self::ZAPDOS_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MOLTRES()
    {
        if (self::$MOLTRES !== null) {
            return self::$MOLTRES;
        }

        return self::$MOLTRES = new self('MOLTRES', self::MOLTRES_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DRATINI()
    {
        if (self::$DRATINI !== null) {
            return self::$DRATINI;
        }

        return self::$DRATINI = new self('DRATINI', self::DRATINI_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DRAGONAIR()
    {
        if (self::$DRAGONAIR !== null) {
            return self::$DRAGONAIR;
        }

        return self::$DRAGONAIR = new self('DRAGONAIR', self::DRAGONAIR_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function DRAGONITE()
    {
        if (self::$DRAGONITE !== null) {
            return self::$DRAGONITE;
        }

        return self::$DRAGONITE = new self('DRAGONITE', self::DRAGONITE_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MEWTWO()
    {
        if (self::$MEWTWO !== null) {
            return self::$MEWTWO;
        }

        return self::$MEWTWO = new self('MEWTWO', self::MEWTWO_VALUE);
    }

    /**
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function MEW()
    {
        if (self::$MEW !== null) {
            return self::$MEW;
        }

        return self::$MEW = new self('MEW', self::MEW_VALUE);
    }

    /**
     * @param int $value
     * @return \PkgClient\Protocol\Enum\PokemonId
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::MISSINGNO();
            case 1: return self::BULBASAUR();
            case 2: return self::IVYSAUR();
            case 3: return self::VENUSAUR();
            case 4: return self::CHARMENDER();
            case 5: return self::CHARMELEON();
            case 6: return self::CHARIZARD();
            case 7: return self::SQUIRTLE();
            case 8: return self::WARTORTLE();
            case 9: return self::BLASTOISE();
            case 10: return self::CATERPIE();
            case 11: return self::METAPOD();
            case 12: return self::BUTTERFREE();
            case 13: return self::WEEDLE();
            case 14: return self::KAKUNA();
            case 15: return self::BEEDRILL();
            case 16: return self::PIDGEY();
            case 17: return self::PIDGEOTTO();
            case 18: return self::PIDGEOT();
            case 19: return self::RATTATA();
            case 20: return self::RATICATE();
            case 21: return self::SPEAROW();
            case 22: return self::FEAROW();
            case 23: return self::EKANS();
            case 24: return self::ARBOK();
            case 25: return self::PIKACHU();
            case 26: return self::RAICHU();
            case 27: return self::SANDSHREW();
            case 28: return self::SANDLASH();
            case 29: return self::NIDORAN_FEMALE();
            case 30: return self::NIDORINA();
            case 31: return self::NIDOQUEEN();
            case 32: return self::NIDORAN_MALE();
            case 33: return self::NIDORINO();
            case 34: return self::NIDOKING();
            case 35: return self::CLEFARY();
            case 36: return self::CLEFABLE();
            case 37: return self::VULPIX();
            case 38: return self::NINETALES();
            case 39: return self::JIGGLYPUFF();
            case 40: return self::WIGGLYTUFF();
            case 41: return self::ZUBAT();
            case 42: return self::GOLBAT();
            case 43: return self::ODDISH();
            case 44: return self::GLOOM();
            case 45: return self::VILEPLUME();
            case 46: return self::PARAS();
            case 47: return self::PARASECT();
            case 48: return self::VENONAT();
            case 49: return self::VENOMOTH();
            case 50: return self::DIGLETT();
            case 51: return self::DUGTRIO();
            case 52: return self::MEOWTH();
            case 53: return self::PERSIAN();
            case 54: return self::PSYDUCK();
            case 55: return self::GOLDUCK();
            case 56: return self::MANKEY();
            case 57: return self::PRIMEAPE();
            case 58: return self::GROWLITHE();
            case 59: return self::ARCANINE();
            case 60: return self::POLIWAG();
            case 61: return self::POLIWHIRL();
            case 62: return self::POLIWRATH();
            case 63: return self::ABRA();
            case 64: return self::KADABRA();
            case 65: return self::ALAKHAZAM();
            case 66: return self::MACHOP();
            case 67: return self::MACHOKE();
            case 68: return self::MACHAMP();
            case 69: return self::BELLSPROUT();
            case 70: return self::WEEPINBELL();
            case 71: return self::VICTREEBELL();
            case 72: return self::TENTACOOL();
            case 73: return self::TENTACRUEL();
            case 74: return self::GEODUGE();
            case 75: return self::GRAVELER();
            case 76: return self::GOLEM();
            case 77: return self::PONYTA();
            case 78: return self::RAPIDASH();
            case 79: return self::SLOWPOKE();
            case 80: return self::SLOWBRO();
            case 81: return self::MAGNEMITE();
            case 82: return self::MAGNETON();
            case 83: return self::FARFETCHD();
            case 84: return self::DODUO();
            case 85: return self::DODRIO();
            case 86: return self::SEEL();
            case 87: return self::DEWGONG();
            case 88: return self::GRIMER();
            case 89: return self::MUK();
            case 90: return self::SHELLDER();
            case 91: return self::CLOYSTER();
            case 92: return self::GASTLY();
            case 93: return self::HAUNTER();
            case 94: return self::GENGAR();
            case 95: return self::ONIX();
            case 96: return self::DROWZEE();
            case 97: return self::HYPNO();
            case 98: return self::KRABBY();
            case 99: return self::KINGLER();
            case 100: return self::VOLTORB();
            case 101: return self::ELECTRODE();
            case 102: return self::EXEGGCUTE();
            case 103: return self::EXEGGUTOR();
            case 104: return self::CUBONE();
            case 105: return self::MAROWAK();
            case 106: return self::HITMONLEE();
            case 107: return self::HITMONCHAN();
            case 108: return self::LICKITUNG();
            case 109: return self::KOFFING();
            case 110: return self::WEEZING();
            case 111: return self::RHYHORN();
            case 112: return self::RHYDON();
            case 113: return self::CHANSEY();
            case 114: return self::TANGELA();
            case 115: return self::KANGASKHAN();
            case 116: return self::HORSEA();
            case 117: return self::SEADRA();
            case 118: return self::GOLDEEN();
            case 119: return self::SEAKING();
            case 120: return self::STARYU();
            case 121: return self::STARMIE();
            case 122: return self::MR_MIME();
            case 123: return self::SCYTHER();
            case 124: return self::JYNX();
            case 125: return self::ELECTABUZZ();
            case 126: return self::MAGMAR();
            case 127: return self::PINSIR();
            case 128: return self::TAUROS();
            case 129: return self::MAGIKARP();
            case 130: return self::GYARADOS();
            case 131: return self::LAPRAS();
            case 132: return self::DITTO();
            case 133: return self::EEVEE();
            case 134: return self::VAPOREON();
            case 135: return self::JOLTEON();
            case 136: return self::FLAREON();
            case 137: return self::PORYGON();
            case 138: return self::OMANYTE();
            case 139: return self::OMASTAR();
            case 140: return self::KABUTO();
            case 141: return self::KABUTOPS();
            case 142: return self::AERODACTYL();
            case 143: return self::SNORLAX();
            case 144: return self::ARTICUNO();
            case 145: return self::ZAPDOS();
            case 146: return self::MOLTRES();
            case 147: return self::DRATINI();
            case 148: return self::DRAGONAIR();
            case 149: return self::DRAGONITE();
            case 150: return self::MEWTWO();
            case 151: return self::MEW();
            default: return null;
        }
    }


}

