<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Message.proto
 */


namespace PkgClient\Protocol\Message;

/**
 * Protobuf message : PkgClient.Protocol.Message.CatchPokemonResponse
 */
class CatchPokemonResponse extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * status optional enum = 1
     *
     * @var \PkgClient\Protocol\Message\CatchPokemonResponse\CatchStatus
     */
    protected $status = null;

    /**
     * miss_percent optional double = 2
     *
     * @var float
     */
    protected $miss_percent = null;

    /**
     * captured_pokemon_id optional uint64 = 3
     *
     * @var int
     */
    protected $captured_pokemon_id = null;

    /**
     * scores optional message = 4
     *
     * @var \PkgClient\Protocol\Message\CaptureScore
     */
    protected $scores = null;

    /**
     * Check if 'status' has a value
     *
     * @return bool
     */
    public function hasStatus()
    {
        return $this->status !== null;
    }

    /**
     * Get 'status' value
     *
     * @return \PkgClient\Protocol\Message\CatchPokemonResponse\CatchStatus
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set 'status' value
     *
     * @param \PkgClient\Protocol\Message\CatchPokemonResponse\CatchStatus $value
     */
    public function setStatus(\PkgClient\Protocol\Message\CatchPokemonResponse\CatchStatus $value = null)
    {
        $this->status = $value;
    }

    /**
     * Check if 'miss_percent' has a value
     *
     * @return bool
     */
    public function hasMissPercent()
    {
        return $this->miss_percent !== null;
    }

    /**
     * Get 'miss_percent' value
     *
     * @return float
     */
    public function getMissPercent()
    {
        return $this->miss_percent;
    }

    /**
     * Set 'miss_percent' value
     *
     * @param float $value
     */
    public function setMissPercent($value = null)
    {
        $this->miss_percent = $value;
    }

    /**
     * Check if 'captured_pokemon_id' has a value
     *
     * @return bool
     */
    public function hasCapturedPokemonId()
    {
        return $this->captured_pokemon_id !== null;
    }

    /**
     * Get 'captured_pokemon_id' value
     *
     * @return int
     */
    public function getCapturedPokemonId()
    {
        return $this->captured_pokemon_id;
    }

    /**
     * Set 'captured_pokemon_id' value
     *
     * @param int $value
     */
    public function setCapturedPokemonId($value = null)
    {
        $this->captured_pokemon_id = $value;
    }

    /**
     * Check if 'scores' has a value
     *
     * @return bool
     */
    public function hasScores()
    {
        return $this->scores !== null;
    }

    /**
     * Get 'scores' value
     *
     * @return \PkgClient\Protocol\Message\CaptureScore
     */
    public function getScores()
    {
        return $this->scores;
    }

    /**
     * Set 'scores' value
     *
     * @param \PkgClient\Protocol\Message\CaptureScore $value
     */
    public function setScores(\PkgClient\Protocol\Message\CaptureScore $value = null)
    {
        $this->scores = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'status' => null,
            'miss_percent' => null,
            'captured_pokemon_id' => null,
            'scores' => null
        ], $values);

        $message->setStatus($values['status']);
        $message->setMissPercent($values['miss_percent']);
        $message->setCapturedPokemonId($values['captured_pokemon_id']);
        $message->setScores($values['scores']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CatchPokemonResponse',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'status',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.PkgClient.Protocol.Message.CatchPokemonResponse.CatchStatus'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'miss_percent',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'captured_pokemon_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'scores',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.PkgClient.Protocol.Message.CaptureScore'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->status !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->status->value());
        }

        if ($this->miss_percent !== null) {
            $writer->writeVarint($stream, 17);
            $writer->writeDouble($stream, $this->miss_percent);
        }

        if ($this->captured_pokemon_id !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->captured_pokemon_id);
        }

        if ($this->scores !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeVarint($stream, $this->scores->serializedSize($sizeContext));
            $this->scores->writeTo($context);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->status = \PkgClient\Protocol\Message\CatchPokemonResponse\CatchStatus::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->miss_percent = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->captured_pokemon_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \PkgClient\Protocol\Message\CaptureScore();

                $this->scores = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->status !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->status->value());
        }

        if ($this->miss_percent !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->captured_pokemon_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->captured_pokemon_id);
        }

        if ($this->scores !== null) {
            $innerSize = $this->scores->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->status = null;
        $this->miss_percent = null;
        $this->captured_pokemon_id = null;
        $this->scores = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \PkgClient\Protocol\Message\CatchPokemonResponse) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->status = ($message->status !== null) ? $message->status : $this->status;
        $this->miss_percent = ($message->miss_percent !== null) ? $message->miss_percent : $this->miss_percent;
        $this->captured_pokemon_id = ($message->captured_pokemon_id !== null) ? $message->captured_pokemon_id : $this->captured_pokemon_id;
        $this->scores = ($message->scores !== null) ? $message->scores : $this->scores;
    }


}

