<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Message.proto
 */


namespace PkgClient\Protocol\Message;

/**
 * Protobuf message : PkgClient.Protocol.Message.InventoryUpgrade
 */
class InventoryUpgrade extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * item optional enum = 1
     *
     * @var \PkgClient\Protocol\Enum\ItemType
     */
    protected $item = null;

    /**
     * upgrade_type optional enum = 2
     *
     * @var \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    protected $upgrade_type = null;

    /**
     * additional_storage optional int32 = 3
     *
     * @var int
     */
    protected $additional_storage = null;

    /**
     * Check if 'item' has a value
     *
     * @return bool
     */
    public function hasItem()
    {
        return $this->item !== null;
    }

    /**
     * Get 'item' value
     *
     * @return \PkgClient\Protocol\Enum\ItemType
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Set 'item' value
     *
     * @param \PkgClient\Protocol\Enum\ItemType $value
     */
    public function setItem(\PkgClient\Protocol\Enum\ItemType $value = null)
    {
        $this->item = $value;
    }

    /**
     * Check if 'upgrade_type' has a value
     *
     * @return bool
     */
    public function hasUpgradeType()
    {
        return $this->upgrade_type !== null;
    }

    /**
     * Get 'upgrade_type' value
     *
     * @return \PkgClient\Protocol\Enum\InventoryUpgradeType
     */
    public function getUpgradeType()
    {
        return $this->upgrade_type;
    }

    /**
     * Set 'upgrade_type' value
     *
     * @param \PkgClient\Protocol\Enum\InventoryUpgradeType $value
     */
    public function setUpgradeType(\PkgClient\Protocol\Enum\InventoryUpgradeType $value = null)
    {
        $this->upgrade_type = $value;
    }

    /**
     * Check if 'additional_storage' has a value
     *
     * @return bool
     */
    public function hasAdditionalStorage()
    {
        return $this->additional_storage !== null;
    }

    /**
     * Get 'additional_storage' value
     *
     * @return int
     */
    public function getAdditionalStorage()
    {
        return $this->additional_storage;
    }

    /**
     * Set 'additional_storage' value
     *
     * @param int $value
     */
    public function setAdditionalStorage($value = null)
    {
        $this->additional_storage = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'item' => null,
            'upgrade_type' => null,
            'additional_storage' => null
        ], $values);

        $message->setItem($values['item']);
        $message->setUpgradeType($values['upgrade_type']);
        $message->setAdditionalStorage($values['additional_storage']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'InventoryUpgrade',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'item',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.PkgClient.Protocol.Enum.ItemType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'upgrade_type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.PkgClient.Protocol.Enum.InventoryUpgradeType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'additional_storage',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->item !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->item->value());
        }

        if ($this->upgrade_type !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->upgrade_type->value());
        }

        if ($this->additional_storage !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->additional_storage);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->item = \PkgClient\Protocol\Enum\ItemType::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->upgrade_type = \PkgClient\Protocol\Enum\InventoryUpgradeType::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->additional_storage = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->item !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->item->value());
        }

        if ($this->upgrade_type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->upgrade_type->value());
        }

        if ($this->additional_storage !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->additional_storage);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->item = null;
        $this->upgrade_type = null;
        $this->additional_storage = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \PkgClient\Protocol\Message\InventoryUpgrade) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->item = ($message->item !== null) ? $message->item : $this->item;
        $this->upgrade_type = ($message->upgrade_type !== null) ? $message->upgrade_type : $this->upgrade_type;
        $this->additional_storage = ($message->additional_storage !== null) ? $message->additional_storage : $this->additional_storage;
    }


}

